"""Renomear titulo para legenda e conteudo para imagem

Revision ID: 00092a407f4f
Revises: 175e3666b881
Create Date: 2025-02-16 19:35:06.174578

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '00092a407f4f'
down_revision = '175e3666b881'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('legenda', sa.String(length=255), nullable=False))
        batch_op.add_column(sa.Column('imagem', sa.String(), nullable=False))
        batch_op.drop_column('titulo')
        batch_op.drop_column('conteudo')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('conteudo', sa.TEXT(), nullable=False))
        batch_op.add_column(sa.Column('titulo', sa.VARCHAR(length=255), nullable=False))
        batch_op.drop_column('imagem')
        batch_op.drop_column('legenda')

    # ### end Alembic commands ###
